### ISSUE TITLE
Q: Reasons for switching from Zig to Rust

### ISSUE THREAD

**Issue by nekrondev** [vrischmann/hdas#4]
Hi Vincent,

not a real issue but more than a question why the change from Zig to Rust version of your service?
Did you miss std library stability or to fix things now and then when master breaks compilation of the old Zig-based version?

Cheers,
Nek

**Comment by vrischmann** [comment]
I wanted to get into rust for some time and thought using this project which is relatively simple but still useful would be a good idea. The zig version was working fine, this is purely to learn rust.

As for your last question, even if it's not the case with this project the zig ecosystem is still incomplete and not mature. The HTTP server I was using has limitations, there are no equivalent to the `time` crate, and more.
I'm still going to write zig code but I also would like to experiment with rust.

Hope that answers your question.

**Comment by nekrondev** [comment]
Thanks for your feedback, I'm in the same boat and try learning and using both languages.
